/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg.library_management_system;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class Book_Add extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private static DefaultTableModel tableModel;
    private TableRowSorter<DefaultTableModel> sorter;

    public Book_Add() {
        initComponents();
        cb_Category.setSelectedIndex(-1);
        initializeTableModel();
        loadBookData();

    }
     private  void initializeTableModel() {
        tableModel = (DefaultTableModel) Table_Book.getModel();
        // Enable sorting
        sorter = new TableRowSorter<>(tableModel);
        Table_Book.setRowSorter(sorter);
    }
     
   private boolean validateInputs(){
         boolean result = false;
         if (tf_isbn.getText().trim().isEmpty() || tf_quantity.getText().trim().isEmpty() ||
            tf_title.getText().trim().isEmpty() || tf_author.getText().trim().isEmpty() ||
            tf_publicationYear.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields.", 
                    "Error", JOptionPane.ERROR_MESSAGE);

        }
        else if (!isValidTitle(tf_title.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a valid book Title.", 
                    "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
        else if (!isValidAuthor(tf_author.getText())){            
            JOptionPane.showMessageDialog(null, "Please enter a valid Author.", 
                    "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
        else if (!isValidPublicationYear(tf_publicationYear.getText())){            
            JOptionPane.showMessageDialog(null, "Please enter a valid Publication Year of 4 digits.", 
                    "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
        else if (!isValidQuantity(tf_quantity.getText())){            
            JOptionPane.showMessageDialog(null, "Please enter a valid Quantity (A positive integer).", 
                    "Invalid input", JOptionPane.ERROR_MESSAGE);
         }
         else
             result =true;
         
         return result;
     }
     
     
     
    public static boolean isValidTitle(String title) {
        // Regex pattern to ensure the title contains only letters and spaces and allows for accented characters like é 
        String titleRegex = "^[\\p{L}0-9 .'-:]+$";
        Pattern pattern = Pattern.compile(titleRegex);
        Matcher matcher = pattern.matcher(title);
        return matcher.matches();
    }

    public static boolean isValidAuthor(String author) {
        // Regex pattern to ensure the author's name contains letters, spaces, numbers, and allows for accented characters like é 
        String authorRegex = "^[\\p{L} .'-:]+$";
        Pattern pattern = Pattern.compile(authorRegex);
        Matcher matcher = pattern.matcher(author);
        return matcher.matches();
    }

    public static boolean isValidPublicationYear(String year) {
        // Regex pattern to ensure the publication year is exactly 4 digits long
        String yearRegex = "^[0-9]{4}$";
        Pattern pattern = Pattern.compile(yearRegex);
        Matcher matcher = pattern.matcher(year);
        return matcher.matches();
    }

    public static boolean isValidQuantity(String quantity) {
        // Regex pattern to ensure the quantity is a positive integer
        String quantityRegex = "^[1-9][0-9]*$";
        Pattern pattern = Pattern.compile(quantityRegex);
        Matcher matcher = pattern.matcher(quantity);
        return matcher.matches();
    }
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_back1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbl_pub_year1 = new javax.swing.JLabel();
        tf_isbn = new javax.swing.JTextField();
        tf_author = new javax.swing.JTextField();
        cb_Category = new javax.swing.JComboBox<>();
        lbl_Quantity1 = new javax.swing.JLabel();
        tf_publicationYear = new javax.swing.JTextField();
        tf_title = new javax.swing.JTextField();
        lbl_category1 = new javax.swing.JLabel();
        lbl_isbn3 = new javax.swing.JLabel();
        tf_quantity = new javax.swing.JTextField();
        lbl_isbn4 = new javax.swing.JLabel();
        lbl_isbn5 = new javax.swing.JLabel();
        btn_Add = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Book = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar1.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashoard bg left.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(445, 981));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashoard bg right.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 32)); // NOI18N
        jLabel1.setText("                         Add Book ");

        btn_back1.setBackground(new java.awt.Color(229, 207, 207));
        btn_back1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btn_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-back-btn-22.png"))); // NOI18N
        btn_back1.setText("BACK  ");
        btn_back1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back1.setBorderPainted(false);
        btn_back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Trebuchet MS", 0, 14))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(420, 300));

        lbl_pub_year1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_pub_year1.setText("Publication Year :");

        tf_isbn.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tf_isbn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_author.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        cb_Category.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cb_Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "History", "Religion", "Coding", "Math", "Islam", "Ahl al-Bayt", "Literature", "Health", "Sociology", "Economy" }));
        cb_Category.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_Category.setFocusCycleRoot(true);
        cb_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CategoryActionPerformed(evt);
            }
        });

        lbl_Quantity1.setText("Quantity :");

        tf_publicationYear.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tf_publicationYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_publicationYearActionPerformed(evt);
            }
        });

        tf_title.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        lbl_category1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_category1.setText("Category :");

        lbl_isbn3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_isbn3.setText("ISBN :");

        tf_quantity.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        lbl_isbn4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_isbn4.setText("Title :");

        lbl_isbn5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_isbn5.setText("Author :");

        btn_Add.setBackground(new java.awt.Color(229, 207, 207));
        btn_Add.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons-add-22.png"))); // NOI18N
        btn_Add.setText("ADD  ");
        btn_Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Add.setBorderPainted(false);
        btn_Add.setFocusPainted(false);
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lbl_Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_isbn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_isbn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbl_pub_year1)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_isbn5)
                                    .addComponent(lbl_category1))))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_title)
                            .addComponent(tf_author, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_publicationYear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_quantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_isbn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_Category, 0, 253, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_isbn3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_isbn4))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_isbn5))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_category1)
                    .addComponent(cb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_publicationYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pub_year1))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Quantity1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_Book.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Title", "Author", "Category", "Publication Year", "Quantity", "Is_borrowed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table_Book);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Enter Book Info :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_back1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1564, 1018));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static void loadBookData(){
        Connection cnt= null;
        Statement stmt = null;
        ResultSet rs = null;
        
        try {
            cnt= jdbc_test.getCon();
            stmt = cnt.createStatement();
            String query = "SELECT * FROM Books";
            rs = stmt.executeQuery(query);

            // Clear the existing data in the table model
            tableModel.setRowCount(0);

            // Populate the table model with the data from the result set
            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                row.add(rs.getString("ISBN"));
                row.add(rs.getString("Title"));
                row.add(rs.getString("Author"));
                row.add(rs.getString("Category"));
                row.add(rs.getString("Publication_year"));
                row.add(rs.getString("Quantity"));
                row.add(rs.getString("Is_borrowed"));

                tableModel.addRow(row);        
            }
        }
        
        catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void cb_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CategoryActionPerformed

    private void tf_publicationYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_publicationYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_publicationYearActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:

        
        if (validateInputs()){
            // Insert into the database
                String ISBN = tf_isbn.getText();
                String quantity = tf_quantity.getText();
                String title = tf_title.getText();
                String author = tf_author.getText();
                String publicationYear = tf_publicationYear.getText();
                String category = cb_Category.getSelectedItem().toString();

                Book b = new Book (ISBN, title, author, quantity, publicationYear , category);
                b.addBook();
               
                loadBookData();
                
            // Clear the text fields
            tf_isbn.setText("");
            tf_quantity.setText("");
            tf_title.setText("");
            tf_author.setText("");
            tf_publicationYear.setText("");
            cb_Category.setSelectedIndex(-1);
        }

    }//GEN-LAST:event_btn_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Book;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_back1;
    private javax.swing.JComboBox<String> cb_Category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Quantity1;
    private javax.swing.JLabel lbl_category1;
    private javax.swing.JLabel lbl_isbn3;
    private javax.swing.JLabel lbl_isbn4;
    private javax.swing.JLabel lbl_isbn5;
    private javax.swing.JLabel lbl_pub_year1;
    private javax.swing.JTextField tf_author;
    private javax.swing.JTextField tf_isbn;
    private javax.swing.JTextField tf_publicationYear;
    private javax.swing.JTextField tf_quantity;
    private javax.swing.JTextField tf_title;
    // End of variables declaration//GEN-END:variables
}
