/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg.library_management_system;

import java.sql.*;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class Student_Add extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private TableRowSorter<DefaultTableModel> sorter;


    public Student_Add() {
        initComponents();
        cb_Faculty.setSelectedIndex(-1);
        initializeTableModel();
        loadStudentData();
    }

     private void initializeTableModel() {
        tableModel = (DefaultTableModel) Table_Student.getModel();
        // Enable sorting
        sorter = new TableRowSorter<>(tableModel);
        Table_Student.setRowSorter(sorter);
    }
     
     private boolean validateInputs(){
         
         boolean result = false;
         if (tf_stdID.getText().trim().isEmpty() || tf_email.getText().trim().isEmpty() ||
        tf_Fname.getText().trim().isEmpty() || tf_midName.getText().trim().isEmpty() ||
        tf_Lname.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);

        }
         else  if (!isValidStudentID(tf_stdID.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a valid Student ID of 5 digits.", "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
         else if (!isValidFirstLastName(tf_Fname.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a valid First Name.", "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
         else if (!isValidMiddleName(tf_midName.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a single letter for the Middle Name.", "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
         else if (!isValidFirstLastName(tf_Lname.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a valid Last Name.", "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
         else if (!isValidPhone(tf_phone.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number.", "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
         else if (!isValidEmail(tf_email.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a valid gmail or hotmail address.", "Invalid input", JOptionPane.ERROR_MESSAGE);

         }
         
         else
             result =true;
         
         return result;
         
     }
     
     
     public boolean isValidStudentID(String studentID) {
    // Regex pattern to ensure the ID is exactly 5 digits long and contains only numbers
    String idRegex = "^[0-9]{5}$";
    Pattern pattern = Pattern.compile(idRegex);
    Matcher matcher = pattern.matcher(studentID);
    return matcher.matches();
}
     public boolean isValidMiddleName(String middleName) {
    // Regex pattern to ensure the middle name is exactly one letter (uppercase or lowercase)
    String middleNameRegex = "^[a-zA-Z]$";
    Pattern pattern = Pattern.compile(middleNameRegex);
    Matcher matcher = pattern.matcher(middleName);
    return matcher.matches();
}
     public boolean isValidFirstLastName(String name) {
    // Regex pattern to ensure the first name or last name only contains letters
    String nameRegex = "^[a-zA-Z]+$"; 
    Pattern pattern = Pattern.compile(nameRegex);
    Matcher matcher = pattern.matcher(name);
    return matcher.matches();
}
     
     public boolean isValidPhone( String phone){
    // Regex pattern to ensure the middle name is exactly one letter (uppercase or lowercase)
    String phoneRegex =  "^[0-9]{8}$";
    Pattern pattern = Pattern.compile(phoneRegex);
    Matcher matcher = pattern.matcher(phone);
    return matcher.matches();         
     }
     
    public boolean isValidEmail(String email) {
    // Regex pattern for emails ending in @gmail.com or @hotmail.com
    String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(gmail|hotmail)\\.com$";
    // Compile the regex
    Pattern pattern = Pattern.compile(emailRegex);
    // Match the email string with the regex pattern
    Matcher matcher = pattern.matcher(email);
    // Return whether it matches the pattern
    return matcher.matches();
          }



     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_back1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Student = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        lbl_pub_year = new javax.swing.JLabel();
        tf_stdID = new javax.swing.JTextField();
        tf_midName = new javax.swing.JTextField();
        lbl_Quantity = new javax.swing.JLabel();
        tf_Lname = new javax.swing.JTextField();
        tf_Fname = new javax.swing.JTextField();
        lbl_category = new javax.swing.JLabel();
        lbl_isbn = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        lbl_isbn1 = new javax.swing.JLabel();
        lbl_isbn2 = new javax.swing.JLabel();
        lbl_Quantity1 = new javax.swing.JLabel();
        tf_phone = new javax.swing.JTextField();
        cb_Faculty = new javax.swing.JComboBox<>();
        btn_Add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar1.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashoard bg left.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(445, 981));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashoard bg right.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 32)); // NOI18N
        jLabel1.setText("                      Add Student ");

        btn_back1.setBackground(new java.awt.Color(229, 207, 207));
        btn_back1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btn_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-back-btn-22.png"))); // NOI18N
        btn_back1.setText("BACK  ");
        btn_back1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back1.setBorderPainted(false);
        btn_back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student_ID", "First Name", "Mid Name", "Last Name", "Email", "Phone", "Faculty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table_Student);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Trebuchet MS", 0, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(420, 300));

        lbl_pub_year.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_pub_year.setText("Email :");

        tf_stdID.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tf_stdID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_midName.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        lbl_Quantity.setText("Phone :");

        tf_Lname.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tf_Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_LnameActionPerformed(evt);
            }
        });

        tf_Fname.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        lbl_category.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_category.setText("Last Name :");

        lbl_isbn.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_isbn.setText("Student_ID: ");

        tf_email.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        lbl_isbn1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_isbn1.setText("First Name :");

        lbl_isbn2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_isbn2.setText("Middle Name :");

        lbl_Quantity1.setText("Faculty :");

        tf_phone.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        cb_Faculty.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cb_Faculty.setMaximumRowCount(7);
        cb_Faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agriculture", "Arts and Humanities", "Business Administration", "Education", "Engineering", "Law", "Public Health", " ", " ", " ", " ", " " }));
        cb_Faculty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_Faculty.setFocusCycleRoot(true);
        cb_Faculty.setOpaque(false);
        cb_Faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_FacultyActionPerformed(evt);
            }
        });

        btn_Add.setBackground(new java.awt.Color(229, 207, 207));
        btn_Add.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons-add-22.png"))); // NOI18N
        btn_Add.setText("ADD  ");
        btn_Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Add.setBorderPainted(false);
        btn_Add.setFocusPainted(false);
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(lbl_category)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_isbn)
                                    .addComponent(lbl_isbn1))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(lbl_isbn2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_pub_year)
                                        .addComponent(lbl_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(tf_midName)
                            .addComponent(tf_Lname)
                            .addComponent(tf_email)
                            .addComponent(tf_stdID)
                            .addComponent(tf_phone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_Faculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_stdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_isbn))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_isbn1))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_midName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_isbn2))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_category))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Quantity1)
                    .addComponent(cb_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Quantity)
                    .addComponent(tf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pub_year)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setText("Enter Student Info :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(272, 272, 272))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_back1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1564, 1018));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadStudentData(){
        Connection cnt= null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            cnt= jdbc_test.getCon();
            stmt = cnt.createStatement();
            String query = "SELECT * FROM student";
            rs = stmt.executeQuery(query);

            // Clear the existing data in the table model
            tableModel.setRowCount(0);

            // Populate the table model with the data from the result set
            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                row.add(rs.getString("std_ID"));
                row.add(rs.getString("Fname"));
                row.add(rs.getString("MidName"));
                row.add(rs.getString("Lname"));
                row.add(rs.getString("Email"));
                row.add(rs.getString("Phone"));
                row.add(rs.getString("Faculty"));

                tableModel.addRow(row);        
            }
        }
        
        catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    
    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
         if (validateInputs()){
             
                // Insert into the database
                String stdID = tf_stdID.getText();
                String Fname = tf_Fname.getText();
                String MidName = tf_midName.getText();
                String Lname = tf_Lname.getText();
                String email = tf_email.getText();
                String phone = tf_phone.getText();
                String faculty = cb_Faculty.getSelectedItem().toString();
                
                Student s = new Student (stdID, Fname, MidName, Lname, email , phone, faculty);
                s.addStudent();
               
                loadStudentData();
                
                // Clear the text fields and selected item
                tf_stdID.setText("");
                tf_email.setText("");
                tf_Fname.setText("");
                tf_midName.setText("");
                tf_Lname.setText("");
                tf_phone.setText(" ");
                cb_Faculty.setSelectedIndex(-1);
            }
         
         
        
           

    }//GEN-LAST:event_btn_AddActionPerformed

    private void tf_LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LnameActionPerformed

    private void cb_FacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_FacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_FacultyActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Student;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_back1;
    private javax.swing.JComboBox<String> cb_Faculty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Quantity;
    private javax.swing.JLabel lbl_Quantity1;
    private javax.swing.JLabel lbl_category;
    private javax.swing.JLabel lbl_isbn;
    private javax.swing.JLabel lbl_isbn1;
    private javax.swing.JLabel lbl_isbn2;
    private javax.swing.JLabel lbl_pub_year;
    private javax.swing.JTextField tf_Fname;
    private javax.swing.JTextField tf_Lname;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_midName;
    private javax.swing.JTextField tf_phone;
    private javax.swing.JTextField tf_stdID;
    // End of variables declaration//GEN-END:variables
}
